name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # Triggers deployment when the master branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd $HOME/ci-cd-demo # Change this to the correct path
            git pull origin master    # Pull latest changes
            npm install               # Install dependencies
            pm2 delete api || true            # Delete API process
            pm2 start index.js --name api  # Restart app using PM2 (or change this to your process manager)
          EOF

